# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"
print(s.split("s"))

['Hi there Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

print("The diameter of {} is {} Kilometers.".format(planet,diameter))

The diameter of Earth is 12742 Kilometers.


## 3. In this nest dictionary grab the word "hello"

In [3]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [5]:


print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
arr =np.zeros(10)
print (arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
arr1=np.ones(10)*5
print(arr1)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
arr=np.arange(20,35,2)
print(arr)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
lis={"Name":["tom","jerry"],"marks":[56,30],"Status":["Pass","Fail"]}
lis

df= pd.DataFrame(lis)
df




Name  marks Status
0    tom     56   Pass
1  jerry     30   Fail

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import datetime
day1= datetime.date(2023,1,1,)
print('day1:',day1.ctime())
day2= datetime.date(2023,2,10)
print('day2:',day2.ctime())
print('Number of days:',day1-day2)

day1: Sun Jan  1 00:00:00 2023
day2: Fri Feb 10 00:00:00 2023
Number of days: -40 days, 0:00:00



## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]


In [ ]:
import  pandas as pd
lst = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
 
df= pd.DataFrame(lst,columns=['colu1','colu2','colu3'])
df

colu1 colu2  colu3
0      1   aaa     22
1      2   bbb     25
2      3   ccc     24