# Basic Python

## 1. Split this string

In [61]:
s = "Hi there Sam!"

In [62]:
p=s.split()
print (p)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [70]:
planet = "Earth"
diameter = 12742

In [73]:
#string function
str1='The diameter of the earth is 12742 kilometres'
str1

'The diameter of the earth is 12742 kilometres'

In [72]:
#strip function
str1.strip()
print (str1)

The diameter of the earth is 12742 kilometres   


## 3. In this nest dictionary grab the word "hello"

In [57]:
#Dictionary

In [63]:
dict1={1:'hello'}
dict1

{1: 'hello'}

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [60]:
import numpy as np
#zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
import numpy as np
np.full((2,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

## 5. Create an array of all the even integers from 20 to 35

In [69]:
import numpy as np
np.arange(20,36,2,dtype='int')

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
import numpy as np
#linespace
a=np.linspace(0,8,9)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [18]:
#reshape
a.reshape(3,3)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [28]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [36]:
import pandas as pd
#DataFrame

In [38]:
d={"Name":['saru','Hari','prasanth'],
"Age":[41,51,29]}
d

{'Name': ['saru', 'Hari', 'prasanth'], 'Age': [41, 51, 29]}

In [54]:
df=pd.DataFrame(d)
df

Name  Key  Age
0  aaa    1   22
1  bbb    2   25
2  ccc    3   24

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [42]:
import pandas as pd
S=pd.Series(np.random.rand(41))

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [50]:
import pandas as pd
#Dataframe

In [52]:
d={"Name":['aaa','bbb','ccc'],"Key":[1,2,3],"Age":[22,25,24]}

In [55]:
df=pd.DataFrame(d)
df

Name  Key  Age
0  aaa    1   22
1  bbb    2   25
2  ccc    3   24